---
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: serverbeacon-api
    main: ./cmd/api
    binary: serverbeacon-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: serverbeacon-api-archive
    builds: [serverbeacon-api]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ end }}
    files:
      - README.md
      # - LICENSE*
      # - config/config.example.toml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dist: dist

release:
  github:
    owner: redjax
    name: serverbeacon
  draft: false
  prerelease: auto

dockers:
  - ids: [serverbeacon-api]
    image_templates:
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-amd64"
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    skip_push: '{{ ne .Env.GITHUB_ACTIONS "true" }}' # Only release Docker container if running in Github Action
  - ids: [serverbeacon-api]
    image_templates:
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    goarch: amd64
  - ids: [serverbeacon-api]
    image_templates:
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}"
    image_templates:
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-amd64"
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/redjax/serverbeacon-api:latest"
    image_templates:
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-amd64"
      - "ghcr.io/redjax/serverbeacon-api:{{ .Tag }}-arm64"
