---
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  ## API binary
  - id: serverbeacon-api
    main: ./cmd/api
    binary: serverbeacon-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  ## CLI binary
  - id: serverbeacon-cli
    main: ./cmd/cli
    binary: serverbeacon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  ## API archive
  - id: serverbeacon-api-archive
    ids: [serverbeacon-api]
    name_template: >-
      {{ .ProjectName }}-api_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - config.yml

  ## CLI archive
  - id: serverbeacon-cli-archive
    ids: [serverbeacon-cli]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - config.yml

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - merge pull request
      - merge branch

dist: dist

release:
  github:
    owner: redjax
    name: serverbeacon
  draft: false
  prerelease: auto

# dockers:
#   - ids: [serverbeacon-api]
#     image_templates:
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-amd64"
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-arm64"
#     dockerfile: dockerfile
#     goos: linux
#     goarch: amd64
#     skip_push: '{{ ne .env.github_actions "true" }}' # only release docker container if running in github action
#   - ids: [serverbeacon-api]
#     image_templates:
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-amd64"
#     dockerfile: dockerfile
#     goarch: amd64
#   - ids: [serverbeacon-api]
#     image_templates:
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-arm64"
#     dockerfile: dockerfile
#     goarch: arm64

# docker_manifests:
#   - name_template: "ghcr.io/redjax/serverbeacon-api:{{ .tag }}"
#     image_templates:
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-amd64"
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-arm64"
#   - name_template: "ghcr.io/redjax/serverbeacon-api:latest"
#     image_templates:
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-amd64"
#       - "ghcr.io/redjax/serverbeacon-api:{{ .tag }}-arm64"
