---
name: serverbeacon

services:
  serverbeacon:
    image: ghcr.io/redjax/serverbeacon:${SERVERBEACON_IMG_TAG:-latest}
    container_name: serverbeacon-api
    command: ["start", "rest-api"]
    ports:
      - ${SERVERBEACON_API_PORT:-18080}:18080
    environment:
      SERVERBEACON_DEBUG: ${SERVERBEACON_DEBUG:-false}
      SERVERBEACON_API_PROTO: ${SERVERBEACON_API_PROTO:-http}
      SERVERBEACON_API_HOST: 0.0.0.0
      SERVERBEACON_API_PORT: 18080
